Default: &defaults
  database: anglais.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: anglais_test.sqlite3
  <<: *defaults

Staging:
  database: anglais_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: anglais_production.sqlite3
  poolsize: 100
  <<: *defaults
